# Generated by Django 5.2.8 on 2025-12-02 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPBIOKEL', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Racion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('gallinas', models.IntegerField()),
                ('alimento_total', models.FloatField()),
            ],
        ),
    ]
